name: wearmask
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  location: ^3.0.0
  intl: ^0.16.1
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  moor_flutter: ^2.0.0
  simple_animations: ^1.3.4
  flutter_local_notifications: ^0.8.4+3
  fluttertoast: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.1.1 
  flutter_launcher_icons: "^0.7.3"
  build_runner:

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/reminder.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:   
   - assets/images/

  fonts:
  - family: SourceSansPro
    fonts:
      - asset: fonts/SourceSansPro-Regular.ttf

  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf